### ISSUE TITLE
Is there a way to pass a style properties also on Placeholder.

### ISSUE THREAD

**Issue by kevzlou7979** [bambora/na-payment-apis-demo#31]
Hi there,

First your api is great, is there a way to stylize the customcheckout input field placeholder.

Best Regards,
Mark

**Comment by pzelnip** [comment]
Hi there, I think https://dev.na.bambora.com/docs/guides/custom_checkout/setup/ is what you're looking for.  You can add styling to the inputs when passing the ```options``` argument to ```customcheckout.create()```.
